<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('perform actions and see result');
$I->amOnPage('/');
$I->maximizeWindow();
$I->waitForElement(['link' => 'Да, я тут'],5);
$I->click(['link' => 'Да, я тут']);
$I->click(['link' => 'Вход']);
$I->fillField('LOGIN', Config::$TEST_LOGIN);
$I->fillField('PASSWORD', Config::$TEST_PASSWORD);
$I->click('Войти');
$I->wait(2);
//$I->waitForElement(['css' => 'div.goods--item'],5);
//$item_id1 = '/goods/id';
//$item_id2 = $I->grabAttributeFrom('//section/div[2]/div/div[2]/div', 'data-xml-id');
//$I->amOnPage($item_id1.$item_id2);
//$I->click(['xpath' => '//section/div[2]/div/div[2]/div']);
$I->click(['css' => 'div.goods--item']);
$I->wait(2);
$item_name = $I->grabTextFrom(['xpath' => '//h1[1]']);
$I->waitForElement(['css' => 'a.offer-card__like'],5);
$I->click(['css' => 'a.offer-card__like']);
$I->waitForElement(['css' => 'a.offer-card__like.active.card__like--active.is-active'],5);
$I->click(['link' => 'Личный кабинет']);
$I->click(['xpath' => '//a[contains(@href, \'/personal/favourite/\')]']);
$I->wait(2);
$I->see($item_name);
$I->click(['css' => 'a.cc-item--like.active.card__like--active.is-active']);
$I->wait(2);
$I->dontSee($item_name);